# Generated by Django 4.2.7 on 2025-10-05 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwallet',
            name='daily_deposit_limit',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='userwallet',
            name='daily_withdrawal_limit',
            field=models.DecimalField(decimal_places=2, default=5000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='userwallet',
            name='mpesa_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userwallet',
            name='paypal_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userwallet',
            name='preferred_payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('paypal', 'PayPal'), ('bank', 'Bank Transfer'), ('crypto', 'Cryptocurrency')], default='mpesa', max_length=10),
        ),
        migrations.AddField(
            model_name='userwallet',
            name='wallet_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('payment', 'Payment'), ('refund', 'Refund')], max_length=10)),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('paypal', 'PayPal'), ('bank', 'Bank Transfer'), ('crypto', 'Cryptocurrency')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('mpesa_code', models.CharField(blank=True, max_length=50, null=True)),
                ('paypal_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
