# Generated by Django 5.2.7 on 2025-10-07 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_userwallet_daily_deposit_limit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('payment', 'Payment'), ('refund', 'Refund'), ('purchase', 'Purchase')], max_length=10),
        ),
        migrations.CreateModel(
            name='Analyst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('experience_years', models.IntegerField(default=0)),
                ('specialization', models.CharField(blank=True, max_length=200, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('total_sales', models.IntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('cryptocurrency', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10)),
                ('analysis_type', models.CharField(choices=[('technical', 'Technical Analysis'), ('fundamental', 'Fundamental Analysis'), ('trading', 'Trading Signals'), ('market', 'Market Research')], max_length=20)),
                ('timeframe', models.CharField(choices=[('short_term', 'Short Term (1-7 days)'), ('medium_term', 'Medium Term (1-4 weeks)'), ('long_term', 'Long Term (1-6 months)')], max_length=20)),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], max_length=10)),
                ('recommendation', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('hold', 'Hold'), ('strong_buy', 'Strong Buy'), ('strong_sell', 'Strong Sell')], default='hold', max_length=15)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_featured', models.BooleanField(default=False)),
                ('discount_percentage', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('executive_summary', models.TextField()),
                ('preview_content', models.TextField(help_text='Content shown in preview mode')),
                ('full_content', models.TextField(help_text='Full analysis content for purchasers')),
                ('technical_indicators', models.JSONField(blank=True, default=dict, null=True)),
                ('chart_patterns', models.JSONField(blank=True, default=list, null=True)),
                ('price_targets', models.JSONField(blank=True, default=dict, null=True)),
                ('fundamental_analysis', models.JSONField(blank=True, default=dict, null=True)),
                ('trading_strategy', models.JSONField(blank=True, default=dict, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('sales_count', models.IntegerField(default=0)),
                ('views_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_premium', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('analyst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.analyst')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.cryptoanalysis'),
        ),
        migrations.CreateModel(
            name='AnalysisRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('review', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.cryptoanalysis')),
            ],
            options={
                'unique_together': {('analysis', 'user')},
            },
        ),
        migrations.CreateModel(
            name='PurchasedAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('access_expires', models.DateTimeField(blank=True, null=True)),
                ('rating_given', models.IntegerField(blank=True, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.cryptoanalysis')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-purchased_at'],
                'unique_together': {('user', 'analysis')},
            },
        ),
    ]
