# Generated by Django 5.2.7 on 2025-10-08 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_consultationpackage_alter_consultation_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analyst',
            name='available_for_consultation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='analyst',
            name='consultation_hours',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='actual_duration',
            field=models.IntegerField(default=0, help_text='Actual duration in minutes'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='follow_up_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultation',
            name='join_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='meeting_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='meeting_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='meeting_platform',
            field=models.CharField(choices=[('jitsi', 'Jitsi Meet'), ('zoom', 'Zoom'), ('google_meet', 'Google Meet'), ('teams', 'Microsoft Teams'), ('custom', 'Custom Link')], default='jitsi', max_length=20),
        ),
        migrations.AddField(
            model_name='consultation',
            name='payment_method',
            field=models.CharField(choices=[('wallet', 'Wallet Balance'), ('mpesa', 'M-Pesa'), ('paypal', 'PayPal'), ('bank', 'Bank Transfer')], default='wallet', max_length=10),
        ),
        migrations.AddField(
            model_name='consultation',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('failed', 'Failed')], default='paid', max_length=20),
        ),
        migrations.AddField(
            model_name='consultation',
            name='rating',
            field=models.IntegerField(blank=True, help_text='User rating 1-5', null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultation',
            name='session_ended',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='session_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', max_length=20),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('no_show', 'No Show')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='consultationpackage',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('paypal', 'PayPal'), ('bank', 'Bank Transfer'), ('crypto', 'Cryptocurrency'), ('wallet', 'Wallet Balance')], max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('payment', 'Payment'), ('refund', 'Refund'), ('purchase', 'Purchase'), ('consultation', 'Consultation')], max_length=15),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='preferred_payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('paypal', 'PayPal'), ('bank', 'Bank Transfer'), ('crypto', 'Cryptocurrency'), ('wallet', 'Wallet Balance')], default='mpesa', max_length=10),
        ),
        migrations.CreateModel(
            name='ConsultationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='consultation_attachments/%Y/%m/%d/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='dashboard.consultation')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification')], max_length=20)),
                ('scheduled_time', models.DateTimeField()),
                ('sent_time', models.DateTimeField(blank=True, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.consultation')),
            ],
            options={
                'ordering': ['scheduled_time'],
            },
        ),
    ]
