# Generated by Django 5.2.7 on 2025-10-10 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_sitesetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cryptoanalysis',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Crypto Analyses'},
        ),
    ]
