# Generated by Django 5.2.7 on 2025-10-10 08:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_cryptoanalysis_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('insight_type', models.CharField(choices=[('market_trend', 'Market Trend'), ('price_analysis', 'Price Analysis'), ('regulatory', 'Regulatory Update'), ('technology', 'Technology Update'), ('adoption', 'Adoption News'), ('security', 'Security Alert')], default='market_trend', max_length=20)),
                ('cryptocurrency', models.CharField(blank=True, max_length=100, null=True)),
                ('symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('summary', models.TextField(help_text='Brief summary of the insight')),
                ('full_content', models.TextField(help_text='Detailed insight content')),
                ('key_takeaways', models.TextField(blank=True, help_text='Key points from the insight')),
                ('impact_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('potential_impact', models.TextField(blank=True, help_text='Potential market impact')),
                ('source', models.CharField(blank=True, max_length=200, null=True)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('views_count', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.analyst')),
            ],
            options={
                'verbose_name': 'Market Insight',
                'verbose_name_plural': 'Market Insights',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
