# Generated by Django 5.2.7 on 2025-10-10 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_marketinsight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cryptoanalysis',
            old_name='technical_indicators',
            new_name='bearish_recommendation',
        ),
        migrations.AddField(
            model_name='cryptoanalysis',
            name='bullish_recommendation',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='cryptoanalysis',
            name='chart_config',
            field=models.JSONField(blank=True, default=dict, help_text='Chart styling and configuration', null=True),
        ),
        migrations.AddField(
            model_name='cryptoanalysis',
            name='chart_data',
            field=models.JSONField(blank=True, default=dict, help_text='JSON data for interactive charts', null=True),
        ),
        migrations.AddField(
            model_name='cryptoanalysis',
            name='chart_image',
            field=models.ImageField(blank=True, null=True, upload_to='analysis_charts/'),
        ),
        migrations.AddField(
            model_name='cryptoanalysis',
            name='chart_type',
            field=models.CharField(choices=[('line', 'Line Chart'), ('candlestick', 'Candlestick Chart'), ('area', 'Area Chart'), ('technical', 'Technical Analysis Chart')], default='candlestick', max_length=20),
        ),
        migrations.AddField(
            model_name='cryptoanalysis',
            name='growth_potential',
            field=models.CharField(default='+24%', help_text='Expected growth percentage', max_length=20),
        ),
        migrations.AddField(
            model_name='cryptoanalysis',
            name='overall_score',
            field=models.DecimalField(decimal_places=1, default=8.0, help_text='Overall score out of 10', max_digits=3),
        ),
        migrations.AddField(
            model_name='cryptoanalysis',
            name='resistance_levels',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='cryptoanalysis',
            name='risk_management_note',
            field=models.TextField(blank=True, help_text='Risk management advice', null=True),
        ),
        migrations.AddField(
            model_name='cryptoanalysis',
            name='support_levels',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='cryptoanalysis',
            name='technical_indicators_json',
            field=models.JSONField(blank=True, default=dict, help_text='Technical indicators configuration', null=True),
        ),
        migrations.CreateModel(
            name='AnalysisInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('importance', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('fundamental', 'Fundamental'), ('sentiment', 'Market Sentiment'), ('risk', 'Risk Assessment'), ('opportunity', 'Trading Opportunity')], default='technical', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='dashboard.cryptoanalysis')),
            ],
            options={
                'ordering': ['-importance', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('current_value', models.CharField(max_length=50)),
                ('previous_value', models.CharField(max_length=50)),
                ('change', models.CharField(max_length=20)),
                ('trend', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('neutral', 'Neutral')], default='neutral', max_length=10)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='dashboard.cryptoanalysis')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChartAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('support', 'Support Level'), ('resistance', 'Resistance Level'), ('entry', 'Entry Point'), ('exit', 'Exit Point'), ('trend', 'Trend Line'), ('pattern', 'Chart Pattern'), ('target', 'Price Target'), ('stop_loss', 'Stop Loss')], max_length=20)),
                ('price_level', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#f0b90b', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_annotations', to='dashboard.cryptoanalysis')),
            ],
            options={
                'ordering': ['price_level'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalIndicatorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_type', models.CharField(choices=[('sma', 'Simple Moving Average'), ('ema', 'Exponential Moving Average'), ('rsi', 'Relative Strength Index'), ('macd', 'Moving Average Convergence Divergence'), ('bollinger', 'Bollinger Bands'), ('stochastic', 'Stochastic Oscillator'), ('volume', 'Volume')], max_length=20)),
                ('data', models.JSONField(default=dict, help_text='Indicator data points')),
                ('parameters', models.JSONField(default=dict, help_text='Indicator parameters (periods, etc.)')),
                ('color', models.CharField(default='#03a66d', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_data', to='dashboard.cryptoanalysis')),
            ],
        ),
    ]
