# Generated by Django 5.2.7 on 2025-10-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_rename_technical_indicators_cryptoanalysis_bearish_recommendation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyst',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
