# Generated by Django 5.2.7 on 2025-10-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_mpesatransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptoanalysis',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
